### ISSUE TITLE
Kill all webDriver sessions

### ISSUE THREAD

**Issue by dmnBrest** [tebeka/selenium#16]
Hello.
Need help with some questions on your lib.
Is there a way to kill running browser from previous session?
If last session wasn't terminated by wd.Quit() - I see browser instance stay in memory and next run just create and kill new session without any affect on old one.
I found this link http://stackoverflow.com/questions/15067107/difference-between-webdriver-dispose-close-and-quit
but don't know how to use Webdriver.Dispose() (If i'm right I need this command).

Thanks for you work. I'm glad to use it.

**Comment by tebeka** [comment]
Thanks for reporting, will take a look soon-ish.

**Comment by tebeka** [comment]
From what I see in [the C# implementation|https://github.com/SeleniumHQ/selenium/blob/master/dotnet/src/webdriver/Remote/RemoteWebDriver.cs#L988] it looks like `Dispose` is just calling `Quit`. You can make sure `Quit` is called by using [defer|https://golang.org/doc/effective_go.html#defer].

It's been a while since I worked with Selenium, not sure is there's a way to get previous sessions other than killing all Chrome/Firefox processes out there.

**Comment by dmnBrest** [comment]
Thank you for information :)
