### ISSUE TITLE
Implicit wait overrides explicit wait

### ISSUE THREAD

**Issue by n8henrie** [tebeka/selenium#182]
```golang
...
wd.SetImplicitWaitTimeout(time.Second * 30)
if err := wd.Get("https://play.golang.org/"); err != nil {
	panic(err)
}
cond := func(wd selenium.WebDriver) (bool, error) {
	_, err := wd.FindElement(selenium.ByXPATH, `//doesnt-exist`)
	if err != nil {
		panic(err)
	}
	return true, nil
}
wd.WaitWithTimeout(cond, time.Second*1)
```

I would expect this to wait with the explicit timeout of `time.Second * 1`, but it seems to wait for the implicit timeout of `time.Second * 30` instead. Is this expected behavior?

EDIT: Though it was perhaps because the closure captures the `SetImplicitWaitTimeout` at definition time, but splitting into a standalone function shows same behavior.

**Comment by Rajagopalan-M** [comment]
@n8henrie  This problem happens whichever language you use for selenium. It happens because implicit wait is set at the level of driver, explicit wait is at the level of program. Since you already set the implicit wait, when you invoke find_element, it would perfectly uses that implicit wait to wait. I would give you an example. If you set implicit wait 60 and explicit wait 61, then driver would wait for 120 seconds because driver releases the control at 60 while element not found, but since explicit wait 61, it would recall find_element method again, so once again, driver would be locked in implicit wait for another 60 seconds.

**Comment by n8henrie** [comment]
Thanks for the explanation. Somewhat counter-intuitive, but seems like it's not a problem with this library.
