### ISSUE TITLE
Switch to alert box

### ISSUE THREAD

**Issue by apoorvam** [tebeka/selenium#40]
Can you tell me how do I switch to alert box from driver? Something like this:

```java
WebDriverWait wait = new WebDriverWait(driver, 2);
        wait.until(ExpectedConditions.alertIsPresent());
        Alert alert = driver.switchTo().alert();
        alert.accept();
```
There is `driver.AcceptAlert()` but this will not be able to get alert unless its switched to alert box.

**Comment by tebeka** [comment]
I'm not sure. Probably with `SetImplicitWaitTimeout` and then `SwitchWindow` to the alert. You'll need to have a look at the Java implementation of `WebDriverWait`.

**Comment by emicklei** [comment]
hi,  to me it is still not clear how to handle this problem.
There is a `SwitchWindow` function in WebDriver but it takes a name parameter, which value for the alert?

btw, the use cases are nicely discussed here: https://www.guru99.com/alert-popup-handling-selenium.html

**Comment by emicklei** [comment]
I did some searching.  

I looked at a Python implementation of the `switch_to_alert`
```
 alert_popup.send_keys(
		  	"{username}{tab}{password}{tab}".format(
		  		username=proxy_username, tab=Keys.TAB, password=proxy_password
		  	)
		  )
```

So I figured, maybe we need an extra Webdriver interface function with implementation such as
```
func (wd *remoteWD) AlertSendKeys(keys string) error {
		return wd.voidCommand("/session/%s/alert/sendkeys", nil)
	}
```

Then I had a look at the Java server implementation whether it supports this command.
The file `selenium-selenium-3.141.59/java/client/src/org/openqa/selenium/remote/http/W3CHttpCommandCodec.java` lists only the current implemented commands:
```
    defineCommand(ACCEPT_ALERT, post("/session/:sessionId/alert/accept"));
    defineCommand(DISMISS_ALERT, post("/session/:sessionId/alert/dismiss"));
    defineCommand(GET_ALERT_TEXT, get("/session/:sessionId/alert/text"));
    defineCommand(SET_ALERT_VALUE, post("/session/:sessionId/alert/text"));
```

Then I had a look at the [W3C standard](https://www.w3.org/TR/webdriver/) and found this list
```
POST | /session/{session id}/alert/dismiss | Dismiss Alert
POST | /session/{session id}/alert/accept | Accept Alert
GET | /session/{session id}/alert/text | Get Alert Text
POST | /session/{session id}/alert/text | Send Alert Text
```

Now it feels like a dead end because it is just not part of the standard.

**Comment by emicklei** [comment]
also tried without success
```
	time.Sleep(5 * time.Second)
	wd.SetAlertText("username=proxy_username\tpassword=proxy_password\t")
```
