### ISSUE TITLE
How do I run chromedriver headlessly?

### ISSUE THREAD

**Issue by budkin** [tebeka/selenium#50]
is it possible?

**Comment by budkin** [comment]
I've found a way
run
```
Xvfb :99
DISPLAY=:99 chromedriver
```

**Comment by satya9500** [comment]
Can you explain a bit more on how you achieved this?

**Comment by tetafro** [comment]
If I understand it correctly the same effect is achieved by using `selenium.StartFrameBuffer()` option - it starts a virtual display, uses it (instead of your real display) while your code is running, and kills it in the end.

[Example](https://github.com/tebeka/selenium/blob/master/example_test.go#L32)

**Comment by liaogang** [comment]
var chromeOpt = chrome.Capabilities{W3C: false}
	chromeOpt.Args = []string{"--headless"}
